web/api/urls.py
from django.conf.urls import include, url
from django.urls import path
from rest_framework import routers

from .views import *

app_name = 'api'
router = routers.DefaultRouter()
router.register(r'listDatatableSubdomain', SubdomainDatatableViewSet, basename='subdomain-datatable')
router.register(r'listTargets', ListTargetsDatatableViewSet, basename='targets')
router.register(r'listSubdomains', SubdomainsViewSet, basename='subdomains')
router.register(r'listEndpoints', EndPointViewSet, basename='endpoints')
router.register(r'listDirectories', DirectoryViewSet, basename='directories')
router.register(r'listVulnerability', VulnerabilityViewSet, basename='vulnerabilities')
router.register(r'listInterestingSubdomains', InterestingSubdomainViewSet, basename='interesting-subdomains')
router.register(r'listInterestingEndpoints', InterestingEndpointViewSet, basename='interesting-endpoints')
router.register(r'listSubdomainChanges', SubdomainChangesViewSet, basename='subdomain-changes')
router.register(r'listEndPointChanges', EndPointChangesViewSet, basename='endpoint-changes')
router.register(r'listIps', IpAddressViewSet, basename='ip-addresses')
router.register(r'listActivityLogs', ListActivityLogsViewSet, basename='activity-logs')
router.register(r'listScanLogs', ListScanLogsViewSet, basename='scan-logs')

urlpatterns = [
    url('^', include(router.urls)),
    path(
        'add/target/',
        AddTarget.as_view(),
        name='addTarget'),
    path(
        'add/recon_note/',
        AddReconNote.as_view(),
        name='addReconNote'),
    path(
        'queryTechnologies/',
        ListTechnology.as_view(),
        name='listTechnologies'),
    path(
        'queryPorts/',
        ListPorts.as_view(),
        name='listPorts'),
    path(
        'queryIps/',
        ListIPs.as_view(),
        name='listIPs'),
    path(
        'queryIp/',
        GetIpDetails.as_view(),
        name='getIpDetails'),
    path(
        'queryInterestingSubdomains/',
        QueryInterestingSubdomains.as_view(),
        name='queryInterestingSubdomains'),
    path(
        'querySubdomains/',
        ListSubdomains.as_view(),
        name='querySubdomains'),
    path(
        'queryScanToolArsenalOutput/',
        GetScanToolArsenalOutput.as_view(),
        name='queryScanToolArsenalOutput'),
    path(
        'queryEndpoints/',
        ListEndpoints.as_view(),
        name='queryEndpoints'),
    path(
        'queryOsintUsers/',
        ListOsintUsers.as_view(),
        name='queryOsintUsers'),
    path(
        'queryMetadata/',
        ListMetadata.as_view(),
        name='queryMetadata'),
    path(
        'queryEmails/',
        ListEmails.as_view(),
        name='queryEmails'),
    path(
        'queryEmployees/',
        ListEmployees.as_view(),
        name='queryEmployees'),
    path(
        'queryDorks/',
        ListDorks.as_view(),
        name='queryDorks'),
    path(
        'queryDorkTypes/',
        ListDorkTypes.as_view(),
        name='queryDorkTypes'),
    path(
        'queryDorkTypes/',
        ListDorkTypes.as_view(),
        name='queryDorkTypes'),
    path(
        'queryAllScanResultVisualise/',
        VisualiseData.as_view(),
        name='queryAllScanResultVisualise'),
    path(
        'fetchScreenshots/',
        FetchScreenshots.as_view(),
        name='fetchScreenshots'),
    path(
        'queryTargetsWithoutOrganization/',
        ListTargetsWithoutOrganization.as_view(),
        name='queryTargetsWithoutOrganization'),
    path(
        'queryTargetsInOrganization/',
        ListTargetsInOrganization.as_view(),
        name='queryTargetsInOrganization'),
    path(
        'listOrganizations/',
        ListOrganizations.as_view(),
        name='listOrganizations'),
    path(
        'listEngines/',
        ListEngines.as_view(),
        name='listEngines'),
    path(
        'listSubScans/',
        ListSubScans.as_view(),
        name='listSubScans'),
    path(
        'listScanHistory/',
        ListScanHistory.as_view(),
        name='listScanHistory'),
    path(
        'listTodoNotes/',
        ListTodoNotes.as_view(),
        name='listTodoNotes'),
    path(
        'listInterestingKeywords/',
        ListInterestingKeywords.as_view(),
        name='listInterestingKeywords'),
    path(
        'getFileContents/',
        GetFileContents.as_view(),
        name='getFileContents'),
    path(
        'vulnerability/report/',
        VulnerabilityReport.as_view(),
        name='vulnerability_report'),
    path(
        'tools/ip_to_domain/',
        IPToDomain.as_view(),
        name='ip_to_domain'),
    path(
        'tools/whois/',
        Whois.as_view(),
        name='whois'),
    path(
        'tools/reverse/whois/',
        ReverseWhois.as_view(),
        name='reverse_whois'),
    path(
        'tools/domain_ip_history',
        DomainIPHistory.as_view(),
        name='domain_ip_history'),
    path(
        'tools/cms_detector/',
        CMSDetector.as_view(),
        name='cms_detector'),
    path(
        'tools/cve_details/',
        CVEDetails.as_view(),
        name='cve_details'),
    path(
        'tools/waf_detector/',
        WafDetector.as_view(),
        name='waf_detector'),
    path(
        'tools/gf_list/',
        GfList.as_view(),
        name='gf_list'),
    path(
        'tools/llm_vulnerability_report/',
        LLMVulnerabilityReportGenerator.as_view(),
        name='llm_vulnerability_report_generator'),
    path(
        'tools/llm_get_possible_attacks/',
        LLMAttackSuggestion.as_view(),
        name='llm_get_possible_attacks'),
    path(
        'tools/llm_models/',
        LLMModelsManager.as_view(),
        name='llm_models_manager'),
    path(
        'tools/available_ollama_models/',
        AvailableOllamaModels.as_view(),
        name='available_ollama_models'),
    path(
        'github/tool/get_latest_releases/',
        GithubToolCheckGetLatestRelease.as_view(),
        name='github_tool_latest_release'),
    path(
        'external/tool/get_current_release/',
        GetExternalToolCurrentVersion.as_view(),
        name='external_tool_get_current_release'),
    path(
        'tool/update/',
        UpdateTool.as_view(),
        name='update_tool'),
    path(
        'tool/uninstall/',
        UninstallTool.as_view(),
        name='uninstall_tool'),
	path(
        'tool/ollama/',
        OllamaManager.as_view(),
        name='ollama_manager'),
    path(
        'tool/ollama/<path:model_name>/',
        OllamaDetailManager.as_view(),
        name='ollama_detail_manager'),        
    path(
        'rengine/update/',
        RengineUpdateCheck.as_view(),
        name='check_rengine_update'),
    path(
        'action/subdomain/delete/',
        DeleteSubdomain.as_view(),
        name='delete_subdomain'),
    path(
        'action/vulnerability/delete/',
        DeleteVulnerability.as_view(),
        name='delete_vulnerability'),
    path(
        'action/rows/delete/',
        DeleteMultipleRows.as_view(),
        name='delete_rows'),
    path(
        'toggle/subdomain/important/',
        ToggleSubdomainImportantStatus.as_view(),
        name='toggle_subdomain'),
    path(
        'action/initiate/subtask/',
        InitiateSubTask.as_view(),
        name='initiate_subscan'),
    path(
        'action/stop/scan/',
        StopScan.as_view(),
        name='stop_scan'),
    path(
        'fetch/results/subscan/',
        FetchSubscanResults.as_view(),
        name='fetch_subscan_results'),
    path(
        'fetch/most_vulnerable/',
        FetchMostVulnerable.as_view(),
        name='fetch_most_vulnerable'),
    path(
        'fetch/most_common_vulnerability/',
        FetchMostCommonVulnerability.as_view(),
        name='fetch_most_common_vulnerability'),
    path(
        'search/',
        UniversalSearch.as_view(),
        name='search'),
    path(
        'search/history/',
        SearchHistoryView.as_view(),
        name='search_history'),
    # API for fetching currently ongoing scans and upcoming scans
    path(
        'scan_status/',
        ScanStatus.as_view(),
        name='scan_status'),
    path(
        'action/create/project',
        CreateProjectApi.as_view(),
        name='create_project'),
    path(
        'uncommon-web-ports/', 
         UncommonWebPortsView.as_view(), 
         name='uncommonWebPorts'),
]

urlpatterns += router.urls

web/reNgine/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from .common_views import permission_denied, page_not_found

schema_view = get_schema_view(
   openapi.Info(
      title="BoltR API",
      default_version='v1',
      description="BoltR: An Automated reconnaissance framework.",
      contact=openapi.Contact(email="yogesh.ojha11@gmail.com"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path(
        'admin/',
        admin.site.urls),
    path(
        '',
        include('dashboard.urls')),
    path(
        'target/',
        include('targetApp.urls')),
    path(
        'scanEngine/',
        include('scanEngine.urls')),
    path(
        'scan/',
        include('startScan.urls')),
    path(
        'recon_note/',
        include('recon_note.urls')),
    path(
        'login/',
        auth_views.LoginView.as_view(template_name='base/login.html'),
        name='login'),
    path(
        'logout/',
        auth_views.LogoutView.as_view(template_name='base/logout.html'),
        name='logout'),
    path(
        'api/',
        include(
            'api.urls',
            'api')),
    path(
        'permission_denied/',
        permission_denied,
        name='permission_denied'),
    path(
        'page_not_found/',
        page_not_found,
        name='page_not_found'),
    path('ws/', include('api.ws_urls')),
] + static(settings.MEDIA_URL, document_root=settings.RENGINE_RESULTS) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

web/templates/base/_items/center_spinner.html
<div class="d-flex justify-content-center">
  <div class="spinner-border" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>

web/templates/base/_items/footer.html
<div class="footer">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6 justify-content-center text-center">
      External IP : {{external_ip}}
    </div>
  </div>
</div>

web/templates/base/_items/green_tick.html
<div class="icon-container text-success">
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check">
    <polyline points="20 6 9 17 4 12"></polyline>
  </svg><span class="icon-name"></span>
</div>

web/templates/base/_items/minus_icon.html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-minus"><line x1="5" y1="12" x2="19" y2="12"></line></svg>

web/templates/base/_items/modal.html
<div class="modal fade" id="modal_dialog" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"></h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="modal-text"></div>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

web/templates/base/_items/most_common_vuln.html
<div class="card" style="height: 95%">
  <div class="card-body">
    <div class="header-title mb-3">
      <div class="row">
        <div class="col-6">
          <h4><span class="text-danger me-1"><i class="fas fa-bug"></i></span>Most Common Vulnerabilities</h4>
        </div>
        <div class="col-6">
          <div class="form-check float-end">
            <input type="checkbox" class="form-check-input" id="ignore_info_most_common_vuln_checkbox">
            <label class="form-check-label" for="ignore_info_most_common_vuln_checkbox">Ignore Info Vulnerabilities</label>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12 mt-1">
        <div class="inbox-widget table-responsive" data-simplebar style="max-height: 407px;">
          <div class="d-flex justify-content-center" id="most_common_vuln_spinner"></div>
          <div id="most_common_vuln_div">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

web/templates/base/_items/most_vuln_target.html
{% load mathfilters %}
<div class="card" style="height: 95%">
  <div class="card-body">
    <div class="header-title mb-3">
      <div class="row">
        <div class="col-6">
          <h4><span class="text-danger me-1"><i class="fas fa-bug"></i></span>{{most_vuln_widget_title}}</h4>
        </div>
        <div class="col-6">
          <div class="form-check float-end">
            <input type="checkbox" class="form-check-input" id="ignore_info_most_vuln_checkbox">
            <label class="form-check-label" for="ignore_info_most_vuln_checkbox">Ignore Info Vulnerabilities</label>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12 mt-1">
        <div class="inbox-widget table-responsive" data-simplebar style="max-height: 407px;">
          <div class="d-flex justify-content-center" id="most_vulnerable_spinner"></div>
          <div id="most_vulnerable_target_div">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

web/templates/base/_items/offcanvas.html
<div class="offcanvas offcanvas-end" data-bs-scroll="true" tabindex="-1" id="offcanvas" aria-labelledby="offcanvasWithBothOptionsLabel">
  <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvas-title"></h5>
      <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body" id="offcanvas-body">
  </div>
</div>

web/templates/base/_items/recon_note_modal.html
<div class="modal fade" id="addSubdomainTaskModal" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Add To-do for <span id="todo-modal-subdomain-name"></span></h4>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="compose-box">
					<div class="compose-content" id="addTaskModalTitle">
						<form>
							<div class="row">
								<div class="col-md-12">
									<div class="d-flex mail-to mb-4">
										<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-3 flaticon-notes"><path d="M12 20h9"></path><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"></path></svg>
										<div class="w-100 ms-2">
											<input id="subdomainTodoTitle" type="text" placeholder="To-do Title" class="form-control" name="task">
										</div>
									</div>
								</div>
							</div>

							<div class="d-flex  mail-subject mb-4">
								<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text flaticon-menu-list"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
								<div class="w-100 ms-2">
									<textarea class="form-control" id="subdomainTodoDescription" rows="5" spellcheck="false" placeholder="Recon To-do/Note"></textarea>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button class="btn btn-primary" id="add-todo-subdomain-submit-button">Add Recon to-do</button>
			</div>
		</div>
	</div>
</div>

web/templates/base/_items/right_bar.html
<div class="right-bar">
  <div data-simplebar class="h-100">
    <div class="tab-content pt-0">
      <div class="tab-pane active" id="tasks-tab" role="tabpanel">
        <ul class="nav nav-tabs nav-bordered mt-3">
          <li class="nav-item active">
            <a href="#tasks" data-bs-toggle="tab" aria-expanded="true" class="nav-link active">
              Scan History
            </a>
          </li>
          <li class="nav-item">
            <a href="#subscan" data-bs-toggle="tab" aria-expanded="false" class="nav-link">
              Tasks
            </a>
          </li>
        </ul>
        <div class="tab-content px-2">
          <div class="tab-pane show active" id="tasks">
            <h6 class="fw-medium mt-1 text-uppercase">Currently Scanning</h6>
            <h5><span class="badge bg-primary rounded-pill" id="current_scan_count"></span></h5>
            <div id="currently_scanning">
            </div>
            <h6 class="fw-medium mt-1 text-uppercase">Recently Completed</h6>
            <div id="completed" class="">
            </div>
            <div class="">
              <a href="{% url 'scan_history' current_project.slug %}" class="float-end">Show All</a>
            </div>
            <br>
            <h6 class="fw-medium mt-2 text-uppercase">Upcoming</h6>
            <div class="">
              <h5><span class="badge bg-warning rounded-pill float-end" id="pending_scan_count"></span></h5>
              <div id="upcoming_scans">
              </div>
            </div>
          </div>

          <div class="tab-pane" id="subscan">
            <h6 class="fw-medium mt-1 text-uppercase">Currently Running</h6>
            <h5><span class="badge bg-primary rounded-pill" id="current_task_count"></span></h5>
            <div id="currently_running_tasks">
            </div>
            <h6 class="fw-medium mt-1 text-uppercase">Recently Completed</h6>
            <div id="completed_tasks" class="">
            </div>
            <div class="">
              <a href="{% url 'subscan_history' current_project.slug %}" class="float-end">Show All</a>
            </div>
            <br>
            <h6 class="fw-medium mt-2 text-uppercase">Upcoming</h6>
            <div class="">
              <h5><span class="badge bg-warning rounded-pill float-end" id="pending_task_count"></span></h5>
              <div id="upcoming_tasks">
              </div>
            </div>
          </div>
          <div class="text-center mt-3 mb-4">
            <a href="javascript:getScanStatusSidebar('{% url 'api:scan_status' %}', '{% url 'api:stop_scan' %}', '{% url 'api:fetch_subscan_results' %}', project='{{current_project.slug}}', reload=true)" class="btn btn-md btn-primary">
              Reload
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

web/templates/base/_items/subscan_modal.html
<div id="subscan-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="standard-modalLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="standard-modalLabel">Initiate subscan</h4>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<div class="mt-2">
					<h5>Select the scan engine <small>(default engine Selected)</small></h5>
					<select class="form-select" id="subtaskScanEngine" name="subtaskScanEngine">
					{% for engine in scan_engines %}
						{% if engine.engine_name == history.scan_type.engine_name %}
							<option value="{{engine.id}}" selected>{{engine}}</option>
							{% else %}
							<option value="{{engine.id}}">{{engine}}</option>
						{% endif %}
					{% endfor %}
					</select>
				</div>
				<h5>Select the engine's subtasks to perform</h5>
				<div id="engineTasks" name="engineTasks">
				<!-- dynamically populated based on engine input -->
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-light" data-bs-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary" id="btn-initiate-subtask"><i class="fe-zap ms-1 me-1"></i>Initiate subscan</button>
			</div>
		</div>
	</div>
</div>

web/templates/base/_items/top_nav.html
{% load permission_tags %}

<div class="topnav" style="position:fixed;top:70px;left:0;right:0;z-index:999;min-height:55px;background:#1f1f1f;display:block!important;visibility:visible!important;">
  <div class="container-fluid">
    <nav class="navbar navbar-light navbar-expand-lg topnav-menu">
      <div class="collapse navbar-collapse show" id="topnav-menu-content" style="display:flex!important;">
        <ul class="navbar-nav">
          <li class="nav-item dropdown {{target_data_active}}">
            <a class="nav-link arrow-none" href="{% url 'dashboardIndex' current_project.slug %}">
              <i class="fe-home me-1"></i> Dashboard
            </a>
          </li>
          <li class="nav-item dropdown {{target_data_active}}">
            <a class="nav-link arrow-none" href="{% url 'list_projects' %}">
              <i class="fe-folder me-1"></i> Projects
            </a>
          </li>
          <li class="nav-item dropdown {{target_data_active}}">
            <a class="nav-link arrow-none" href="{% url 'list_target' current_project.slug %}">
              <i class="fe-crosshair me-1"></i> Targets
            </a>
          </li>
          <li class="nav-item dropdown {{scan_history_active}} {{scheduled_scan_active}}">
            <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-history" role="button"
              data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fe-activity me-1"></i> Scan History
              <div class="arrow-down"></div>
            </a>
            <div class="dropdown-menu" aria-labelledby="topnav-history">
              <a href="{% url 'scan_history' current_project.slug %}" class="dropdown-item">Scan History</a>
              <a href="{% url 'subscan_history' current_project.slug %}" class="dropdown-item">Sub Scan History</a>
              <a href="{% url 'scheduled_scan_view' current_project.slug %}" class="dropdown-item">Scheduled Scan</a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'all_subdomains' current_project.slug %}" class="dropdown-item">All Subdomains</a>
              <a href="{% url 'all_endpoints' current_project.slug %}" class="dropdown-item">All Endpoints</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link arrow-none" href="{% url 'all_vulns' current_project.slug %}">
              <i class="fe-alert-triangle me-1"></i> Vulnerabilities
            </a>
          </li>
          <li class="nav-item dropdown {{recon_note_active}}">
            <a class="nav-link arrow-none" href="{% url 'list_note' current_project.slug %}">
              <i class="fe-check-square me-1"></i> To-do
            </a>
          </li>
          <li class="nav-item dropdown {{organization_active}}">
            <a class="nav-link arrow-none" href="{% url 'list_organization' current_project.slug %}">
              <i class="fe-briefcase me-1"></i> Organization
            </a>
          </li>
          <li class="nav-item dropdown {{scan_engine_nav_active}}">
            <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-scanengine" role="button"
              data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fe-cpu me-1"></i> Scan Engine
              <div class="arrow-down"></div>
            </a>
            <div class="dropdown-menu" aria-labelledby="topnav-scanengine">
              {% if user|can:'modify_scan_configurations' %}
              <a href="{% url 'scan_engine_index' %}" class="dropdown-item">Scan Engines</a>
              {% endif %}
              {% if user|can:'modify_wordlists' %}
              <a href="{% url 'wordlist_list' %}" class="dropdown-item">Wordlists</a>
              {% endif %}
              {% if user|can:'modify_interesting_lookup' %}
              <a href="{% url 'interesting_lookup' %}" class="dropdown-item">Interesting Lookup</a>
              {% endif %}
            </div>
          </li>
          <li class="nav-item dropdown {{settings_nav_active}}">
            <a class="nav-link dropdown-toggle arrow-none" href="#" id="topnav-settings" role="button"
              data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fe-settings me-1"></i> Settings
              <div class="arrow-down"></div>
            </a>
            <div class="dropdown-menu" aria-labelledby="topnav-settings">
              {% if user|can:'modify_scan_configurations' %}
              <a href="{% url 'proxy_settings' %}" class="dropdown-item">Proxies</a>
              <a href="{% url 'tool_settings' %}" class="dropdown-item">Tool Settings</a>
              {% endif %}
              {% if user|can:'modify_system_configurations' %}
              <a href="{% url 'api_vault' %}" class="dropdown-item">API Vault</a>
              <a href="{% url 'llm_toolkit' %}" class="dropdown-item">LLM Toolkit</a>
              <a href="{% url 'tool_arsenal' %}" class="dropdown-item">Tools Arsenal</a>
              {% endif %}
              {% if user|can:'modify_scan_report' %}
              <a href="{% url 'report_settings' %}" class="dropdown-item">Report Settings</a>
              {% endif %}
              {% if user|can:'modify_system_configurations' %}
              <a href="{% url 'rengine_settings' %}" class="dropdown-item">BoltR Settings</a>
              {% endif %}
              {% if user|can:'modify_scan_configurations' %}
              <a href="{% url 'notification_settings' %}" class="dropdown-item">Notification Settings</a>
              {% endif %}
            </div>
          </li>
        </ul>
      </div>
      <span class="badge bg-blue" data-bs-toggle="tooltip" data-bs-placement="top" title="Current Project">{{current_project.name}}</span>
    </nav>
  </div>
</div>